version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - POSTGRES_CONN_STR=postgres://girish:test123@db:5432/postgres
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=girish
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: