name: Packer Validate

on:
  pull_request:
    branches: [ "main" ]


jobs:
  packer-fmt-and-validate:
    needs: test
    environment: Dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup

      - name: Run `packer init`
        id: init
        run: "packer init ./packer/packer.pkr.hcl"

      - name: Run packer fmt
        id: fmt
        run: |
          cd ./packer
          packer fmt -check .

      - name: Run packer validate
        id: validate
        run: |
          set -e
          cd ./packer
          packer validate .