name: Packer Validate

on:
  pull_request:
    branches: [ "main" ]


jobs:
  packer-fmt-and-validate:
    environment: Dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Packer
        run: |
          curl -o packer.zip https://releases.hashicorp.com/packer/1.7.8/packer_1.7.8_linux_amd64.zip
          unzip packer.zip
          sudo mv packer /usr/local/bin/

      - name: Run packer fmt
        run: |
          packer fmt -check

      - name: Run packer validate
        run: |
          packer validate .

